db_assignment/clients/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.client_list, name='client_list'),
    path('view/<int:pk>', views.client_view, name='client_view'),
    path('new', views.client_create, name='client_new'),
    path('edit/<int:pk>', views.client_update, name='client_edit'),
    path('delete/<int:pk>', views.client_delete, name='client_delete'),
    path('search/', views.client_search, name='client_search'),
    path('sort/', views.client_sort, name='client_sort')
]

db_assignment/db_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

admin.autodiscover()

urlpatterns = [

    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('animals/', include('animals.urls')),
    path('species/', include('species.urls')),
    path('vets/', include('vets.urls')),
    path('diagnoses/', include('diagnoses.urls')),
    path('appointments/', include('appointments.urls')),
    path('medicalprocedures/', include('medicalprocedures.urls')),
    path('medications/', include('medications.urls')),
    path('notes/', include('notes.urls')),
    path('diagnosesmedications/', include('diagnosesmedications.urls')),
    path('dignosesprocedures/', include('diagnosesprocedures.urls')),
    path('', include('clients.urls'))
    
]

db_assignment/vets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.vet_list, name='vet_list'),
    path('view/<int:pk>', views.vet_view, name='vet_view'),
    path('new', views.vet_create, name='vet_new'),
    path('edit/<int:pk>', views.vet_update, name='vet_edit'),
    path('delete/<int:pk>', views.vet_delete, name='vet_delete'),
    path('search', views.vet_search, name='vet_search'),
    path('sort/', views.vet_sort, name='vet_sort')
]

db_assignment/models/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.urls import reverse
from django.db import connection

from models.validators import validate_positive


class Client(models.Model):
    clientid = models.AutoField(db_column='ClientID', primary_key=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20)  # Field name made lowercase.
    registrationdate = models.DateField(db_column='RegistrationDate')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Clients'

    def __str__(self):
        return self.firstname + " " + self.lastname

    def get_absolute_url(self):
        return reverse('client_edit', kwargs={'pk': self.pk})




class Animal(models.Model):
    animalid = models.AutoField(db_column='AnimalID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    registrationdate = models.DateField(db_column='RegistrationDate')  # Field name made lowercase.
    birth = models.DateField(db_column='Birth')  # Field name made lowercase.
    gender = models.CharField(db_column='Gender', max_length=6)  # Field name made lowercase.
    height = models.FloatField(db_column='Height', validators=[validate_positive])  # Field name made lowercase.
    weight = models.FloatField(db_column='Weight', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.
    client = models.ForeignKey('Client', models.CASCADE, db_column='Clients_ClientID')  # Field name made lowercase.
    species = models.ForeignKey('Species', models.CASCADE, db_column='Species_Name')  # Field name made lowercase.
    vet = models.ForeignKey('Vet', models.SET_NULL, db_column='Vets_VetID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Animals'

    def __str__(self):
        return self.name

    def _get_last_visit(self):
        with connection.cursor() as cursor:
            cursor.execute("select last_visit(%s)", [self.pk])
            row = cursor.fetchone()
        if row == (None,):
            return "Never"

        return row[0]

    last_visit = property(_get_last_visit)



class Appointment(models.Model):
    appointmentid = models.AutoField(db_column='AppointmentID', primary_key=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date')  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    details = models.CharField(db_column='Details', max_length=20)  # Field name made lowercase.
    vet = models.ForeignKey('Vet', models.CASCADE, db_column='Vets_VetID')  # Field name made lowercase.
    animal = models.ForeignKey(Animal, models.CASCADE, db_column='Animals_AnimalID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Appointments'

    def __str__(self):
        return str(self.date) + " " + str(self.vet) + " " + str(self.animal)

    def custom_save(self):
        with connection.cursor() as cursor:
            cursor.callproc('new_visit', [self.date, self.status, self.details, self.vet.pk, self.animal.pk])
            row = cursor.fetchone()
        return row



class Diagnosis(models.Model):
    diagnosisid = models.AutoField(db_column='DiagnosisID', primary_key=True)  # Field name made lowercase.
    code = models.CharField(db_column='Code', max_length=20)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    treatment = models.CharField(db_column='Treatment', max_length=200)  # Field name made lowercase.
    appointment = models.ForeignKey(Appointment, models.CASCADE, db_column='Appointments_AppointmentID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Diagnoses'

    def __str__(self):
        return "diagnosis " + str(self.pk) + self.description

class MedicalProcedure(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MedicalProcedures'

    def __str__(self):
        return self.name + " " + str(self.cost)


class Medication(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Medications'

    def __str__(self):
        return self.name + " " + str(self.cost)

class DiagnosisMedicalProcedure(models.Model):
    diagnosis_medicalprocedureid = models.AutoField(db_column='Diagnoses_MedicalProceduresID', primary_key=True)  # Field name made lowercase.
    diagnosis = models.ForeignKey(Diagnosis, models.CASCADE, db_column='Diagnoses_DiagnosisID')  # Field name made lowercase.
    medicalprocedure = models.ForeignKey('MedicalProcedure', models.CASCADE, db_column='MedicalProcedures_Name')

    class Meta:
        managed = False
        db_table = 'Diagnoses_MedicalProcedures'

    def __str__(self):
        return  self.medicalprocedure.name + " " + str(self.medicalprocedure.cost)


class DiagnosisMedication(models.Model):
    diagnosis_medicationid = models.AutoField(db_column='Diagnoses_MedicationsID', primary_key=True)  # Field name made lowercase.
    medication = models.ForeignKey('Medication', models.CASCADE, db_column='Medications_Name')  # Field name made lowercase.
    diagnosis = models.ForeignKey(Diagnosis, models.CASCADE, db_column='Diagnoses_DiagnosisID')

    class Meta:
        managed = False
        db_table = 'Diagnoses_Medications'

    def __str__(self):
        return  self.medication.name + " " + str(self.medication.cost)


class Note(models.Model):
    noteid = models.AutoField(db_column='NoteID', primary_key=True)  # Field name made lowercase.
    date = models.DateField(db_column='NoteDate')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=200)  # Field name made lowercase.
    animal = models.ForeignKey(Animal, models.CASCADE, db_column='Animals_AnimalID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Notes'

    def get_absolute_url(self):
        return reverse('note_edit', kwargs={'pk': self.pk})

    def __str__(self):
        return "note " + self.pk + str(self.date)


class Species(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    obligatoryprocedures = models.CharField(db_column='ObligatoryProcedures', max_length=20)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200)  # Field name made lowercase.
    legalissues = models.CharField(db_column='LegalIssues', max_length=200)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Species'

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('species_edit', kwargs={'pk': self.pk})


class Vet(models.Model):
    vetid = models.AutoField(db_column='VetID', primary_key=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20)  # Field name made lowercase.
    qualifications = models.CharField(db_column='Qualifications', max_length=20)  # Field name made lowercase.
    birth = models.DateField(db_column='Birth')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Vets'

    def __eq__(self, other):
        return str(self) == str(other)

    def __lt__(self, other):
        return str(self) < str(other)


    def __gt__(self, other):
        return str(self) > str(other)


    def __str__(self):
        return self.firstname + " " + self.lastname

    def get_absolute_url(self):
        return reverse('vet_edit', kwargs={'pk': self.pk})

db_assignment/clients/views.py
from django.forms import ModelForm
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from operator import attrgetter

# Create your views here.
from models.models import Client


# Function Based Views
class ClientForm(ModelForm): # formularz do tworzenia/edycji klienta
    class Meta:
        model = Client
        fields = ['firstname', 'lastname', 'registrationdate']
        labels = {
            'firstname' : 'First Name',
            'lastname' : 'Last Name',
            'registrationdate' : 'Registration Date (YYYY-MM-DD)'
        }

def client_list(request, template_name='clients/client_list.html'):
    client = Client.objects.all()
    data = {}
    data['object_list'] = client
    return render(request, template_name, data)


def client_view(request, pk, template_name='clients/client_detail.html'):
    client = get_object_or_404(Client,pk=pk)
    return render(request, template_name, {'object':client})


def client_create(request, template_name='clients/client_form.html'):
    form = ClientForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('client_view', form.instance.pk)
    return render(request,template_name, {'form':form})


def client_update(request, pk , template_name='clients/client_form.html'):
    client = get_object_or_404(Client, pk=pk)
    form = ClientForm(request.POST or None, instance=client)
    if form.is_valid():
        form.save()
        return redirect('client_view', pk)
    return render(request,template_name, {'form':form})


def client_delete(request, pk, template_name='clients/client_confirm_delete.html'):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        client.delete()
        return redirect('client_list')
    return render(request,template_name,{'object':client})


def client_search(request, template_name='clients/client_search.html'):
    query = request.GET.get('q')
    results = Client.objects.filter(Q(firstname__icontains=query) |Q(lastname__icontains=query) | Q(registrationdate__icontains=query))
    data={}
    data['object_list'] = results
    return render(request, template_name, data)


def client_sort(request, template_name='clients/client_sort.html'):
    results = Client.objects.all()
    data = {}
    if 'dropdown' in request.GET:
        answer = request.GET['dropdown']
        data['object_list'] = sorted(results, key=attrgetter(answer))
    else:
        data['object_list'] = results
    return render(request, template_name, data)

db_assignment/clients/templates/clients/client_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Client Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

db_assignment/clients/templates/clients/client_detail.html
{% extends "base.html" %}
{% block content %}
<h1>Client Details</h1>
<h2>Name: {{object.firstname}} {{ object.lastname }}</h2>
<h3>Registration Date: {{ object.registrationdate }}</h3>
<h3>Animals:</h3>

<table class="pure-table"1>
<thead>
    <tr>
        <th>Species</th>
        <th>Name</th>
        <th>Birth</th>
        <th>Gender</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
        <th>New appointment</th>

    </tr>
</thead>
<tbody>
    {% for animal in object.animal_set.all %}
        <tr>
            <td>{{ animal.species }}</td>
            <td>{{ animal.name }}</td>
            <td>{{ animal.birth }}</td>
            <td>{{ animal.gender }}</td>
            <td><button class="pure-button" onclick="location.href='{% url "animal_view" animal.pk %}'" type="button">view</button></td>
            <td><button class="pure-button" onclick="location.href='{% url "animal_edit" animal.pk %}'" type="button">edit</button></td>
            <td><button class="pure-button" onclick="location.href='{% url "animal_delete" animal.pk %}'" type="button">delete</button></td>
            <td><button class="pure-button" onclick="location.href='{% url "appointment_new_for_animal" animal.pk %}'" type="button">new appointment</button></td>
        </tr>
    {% endfor %}
</tbody>
</table>
    <button class="pure-button" onclick="location.href='{% url "animal_new_for_client" object.pk %}'" type="button">Add a new animal</button>
<h3>Appointments:</h3>

<table class="pure-table"1>
<thead>
    <tr>
        <th>Date</th>
        <th>Vet</th>
        <th>Name</th>
        <th>Species</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for animal in object.animal_set.all %}
        {% for appointment in animal.appointment_set.all %}
        <tr>
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.vet }}</td>
            <td>{{ animal.name }}</td>
            <td>{{ animal.species }}</td>
            <td><button class="pure-button" onclick="location.href='{% url "appointment_view" appointment.pk %}'" type="button">view</button></td>
            <td><button class="pure-button" onclick="location.href='{% url "appointment_edit" appointment.pk %}'" type="button">edit</button></td>
            <td><button class="pure-button" onclick="location.href='{% url "appointment_delete" appointment.pk %}'" type="button">delete</button></td>
        </tr>
        {% endfor %}
    {% endfor %}
</tbody>
</table>
{% endblock %}

db_assignment/clients/templates/clients/client_form.html
{% extends "base.html" %}

{% block content %}

<h1>Client Edit</h1>
<form class="pure-form" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

db_assignment/clients/templates/clients/client_list.html
{% extends "base.html" %}
{% block content %}


<h1>Clients</h1>


<form method="GET" action="{% url 'client_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<form method="GET" action="{% url 'client_sort' %}">
    <select name="dropdown">
        <option selected="selected" disabled>Sort by:</option>
        <option value="firstname">First Name</option>
        <option value="lastname">Last Name</option>
        <option value="registrationdate">Registration Date</option>
    </select>
    <input type="submit" value="Ok">
</form>

{#<table class="pure-table">#}
<table class="pure-table">
<thead>
    <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Registration Date</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for client in object_list %}
    <tr>
    <td>{{ client.firstname }}</td>
    <td>{{ client.lastname }}</td>
    <td>{{ client.registrationdate }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "client_view" client.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "client_edit" client.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "client_delete" client.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

    <button class="pure-button" onclick="location.href='{% url "client_new" %}'" type="button">New Client</button>

{% endblock %}

db_assignment/clients/templates/clients/client_search.html
{% extends "base.html" %}

{% block content %}
<h1>Results</h1>


<form method="GET" action="{% url 'client_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Fist Name</th>
    <th>Last Name</th>
    <th>Registration Date</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for results in object_list %}
    <tr>
    <td>{{ results.firstname }}</td>
    <td>{{ results.lastname }}</td>
    <td>{{ results.registrationdate }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "client_view" results.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "client_edit" results.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "client_delete" results.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

<button class="pure-button" onclick="location.href='{% url "client_new" %}'" type="button">New Client</button>
{% endblock %}

db_assignment/clients/templates/clients/client_sort.html
{% extends "base.html" %}
{% block content %}

<h1>Clients</h1>

<form method="GET" action="{% url 'client_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<form method="GET" action="{% url 'client_sort' %}">
    <select name="dropdown">
        <option selected="selected" disabled>Sort by:</option>
        <option value="firstname">First Name</option>
        <option value="lastname">Last Name</option>
        <option value="registrationdate">Registration Date</option>
    </select>
    <input type="submit" value="Ok">
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Fist Name</th>
    <th>Last Name</th>
    <th>Registration Date</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for results in object_list %}
    <tr>
    <td>{{ results.firstname }}</td>
    <td>{{ results.lastname }}</td>
    <td>{{ results.registrationdate }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "client_view" results.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "client_edit" results.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "client_delete" results.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>
    <button class="pure-button" onclick="location.href='{% url "client_new" %}'" type="button">New Client</button>
{% endblock %}