db_assignment/db_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

admin.autodiscover()

urlpatterns = [

    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('animals/', include('animals.urls')),
    path('species/', include('species.urls')),
    path('vets/', include('vets.urls')),
    path('diagnoses/', include('diagnoses.urls')),
    path('appointments/', include('appointments.urls')),
    path('medicalprocedures/', include('medicalprocedures.urls')),
    path('medications/', include('medications.urls')),
    path('notes/', include('notes.urls')),
    path('diagnosesmedications/', include('diagnosesmedications.urls')),
    path('dignosesprocedures/', include('diagnosesprocedures.urls')),
    path('', include('clients.urls'))
    
]

db_assignment/diagnoses/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.diagnosis_list, name='diagnosis_list'),
    path('view/<int:pk>', views.diagnosis_view, name='diagnosis_view'),
    path('new', views.diagnosis_create, name='diagnosis_new'),
    path('new/<int:appointmentpk>', views.diagnosis_create_for_appointment, name='diagnosis_new_for_appointment'),
    path('edit/<int:pk>', views.diagnosis_update, name='diagnosis_edit'),
    path('delete/<int:pk>', views.diagnosis_delete, name='diagnosis_delete'),
    path('search', views.diagnosis_search, name='diagnosis_search'),
    path('sort/', views.diagnosis_sort, name="diagnosis_sort")
]

db_assignment/vets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.vet_list, name='vet_list'),
    path('view/<int:pk>', views.vet_view, name='vet_view'),
    path('new', views.vet_create, name='vet_new'),
    path('edit/<int:pk>', views.vet_update, name='vet_edit'),
    path('delete/<int:pk>', views.vet_delete, name='vet_delete'),
    path('search', views.vet_search, name='vet_search'),
    path('sort/', views.vet_sort, name='vet_sort')
]

db_assignment/models/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.urls import reverse
from django.db import connection

from models.validators import validate_positive


class Client(models.Model):
    clientid = models.AutoField(db_column='ClientID', primary_key=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20)  # Field name made lowercase.
    registrationdate = models.DateField(db_column='RegistrationDate')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Clients'

    def __str__(self):
        return self.firstname + " " + self.lastname

    def get_absolute_url(self):
        return reverse('client_edit', kwargs={'pk': self.pk})




class Animal(models.Model):
    animalid = models.AutoField(db_column='AnimalID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    registrationdate = models.DateField(db_column='RegistrationDate')  # Field name made lowercase.
    birth = models.DateField(db_column='Birth')  # Field name made lowercase.
    gender = models.CharField(db_column='Gender', max_length=6)  # Field name made lowercase.
    height = models.FloatField(db_column='Height', validators=[validate_positive])  # Field name made lowercase.
    weight = models.FloatField(db_column='Weight', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.
    client = models.ForeignKey('Client', models.CASCADE, db_column='Clients_ClientID')  # Field name made lowercase.
    species = models.ForeignKey('Species', models.CASCADE, db_column='Species_Name')  # Field name made lowercase.
    vet = models.ForeignKey('Vet', models.SET_NULL, db_column='Vets_VetID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Animals'

    def __str__(self):
        return self.name

    def _get_last_visit(self):
        with connection.cursor() as cursor:
            cursor.execute("select last_visit(%s)", [self.pk])
            row = cursor.fetchone()
        if row == (None,):
            return "Never"

        return row[0]

    last_visit = property(_get_last_visit)



class Appointment(models.Model):
    appointmentid = models.AutoField(db_column='AppointmentID', primary_key=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date')  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    details = models.CharField(db_column='Details', max_length=20)  # Field name made lowercase.
    vet = models.ForeignKey('Vet', models.CASCADE, db_column='Vets_VetID')  # Field name made lowercase.
    animal = models.ForeignKey(Animal, models.CASCADE, db_column='Animals_AnimalID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Appointments'

    def __str__(self):
        return str(self.date) + " " + str(self.vet) + " " + str(self.animal)

    def custom_save(self):
        with connection.cursor() as cursor:
            cursor.callproc('new_visit', [self.date, self.status, self.details, self.vet.pk, self.animal.pk])
            row = cursor.fetchone()
        return row



class Diagnosis(models.Model):
    diagnosisid = models.AutoField(db_column='DiagnosisID', primary_key=True)  # Field name made lowercase.
    code = models.CharField(db_column='Code', max_length=20)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    treatment = models.CharField(db_column='Treatment', max_length=200)  # Field name made lowercase.
    appointment = models.ForeignKey(Appointment, models.CASCADE, db_column='Appointments_AppointmentID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Diagnoses'

    def __str__(self):
        return "diagnosis " + str(self.pk) + self.description

class MedicalProcedure(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MedicalProcedures'

    def __str__(self):
        return self.name + " " + str(self.cost)


class Medication(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Medications'

    def __str__(self):
        return self.name + " " + str(self.cost)

class DiagnosisMedicalProcedure(models.Model):
    diagnosis_medicalprocedureid = models.AutoField(db_column='Diagnoses_MedicalProceduresID', primary_key=True)  # Field name made lowercase.
    diagnosis = models.ForeignKey(Diagnosis, models.CASCADE, db_column='Diagnoses_DiagnosisID')  # Field name made lowercase.
    medicalprocedure = models.ForeignKey('MedicalProcedure', models.CASCADE, db_column='MedicalProcedures_Name')

    class Meta:
        managed = False
        db_table = 'Diagnoses_MedicalProcedures'

    def __str__(self):
        return  self.medicalprocedure.name + " " + str(self.medicalprocedure.cost)


class DiagnosisMedication(models.Model):
    diagnosis_medicationid = models.AutoField(db_column='Diagnoses_MedicationsID', primary_key=True)  # Field name made lowercase.
    medication = models.ForeignKey('Medication', models.CASCADE, db_column='Medications_Name')  # Field name made lowercase.
    diagnosis = models.ForeignKey(Diagnosis, models.CASCADE, db_column='Diagnoses_DiagnosisID')

    class Meta:
        managed = False
        db_table = 'Diagnoses_Medications'

    def __str__(self):
        return  self.medication.name + " " + str(self.medication.cost)


class Note(models.Model):
    noteid = models.AutoField(db_column='NoteID', primary_key=True)  # Field name made lowercase.
    date = models.DateField(db_column='NoteDate')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=200)  # Field name made lowercase.
    animal = models.ForeignKey(Animal, models.CASCADE, db_column='Animals_AnimalID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Notes'

    def get_absolute_url(self):
        return reverse('note_edit', kwargs={'pk': self.pk})

    def __str__(self):
        return "note " + self.pk + str(self.date)


class Species(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    obligatoryprocedures = models.CharField(db_column='ObligatoryProcedures', max_length=20)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200)  # Field name made lowercase.
    legalissues = models.CharField(db_column='LegalIssues', max_length=200)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Species'

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('species_edit', kwargs={'pk': self.pk})


class Vet(models.Model):
    vetid = models.AutoField(db_column='VetID', primary_key=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20)  # Field name made lowercase.
    qualifications = models.CharField(db_column='Qualifications', max_length=20)  # Field name made lowercase.
    birth = models.DateField(db_column='Birth')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Vets'

    def __eq__(self, other):
        return str(self) == str(other)

    def __lt__(self, other):
        return str(self) < str(other)


    def __gt__(self, other):
        return str(self) > str(other)


    def __str__(self):
        return self.firstname + " " + self.lastname

    def get_absolute_url(self):
        return reverse('vet_edit', kwargs={'pk': self.pk})

db_assignment/diagnoses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import ModelForm
from django import forms
from models.models import Diagnosis, Animal, Appointment
from django.db.models import Q
from operator import attrgetter


class DiagnosisForm(ModelForm):
    class Meta:
        model = Diagnosis
        fields = ['code', 'description', 'status', 'treatment']
        widgets = {
            'description': forms.Textarea(attrs={ 'class' : 'text-input', 'size':200}),
            'treatment': forms.Textarea(attrs={'class': 'text-input', 'size': 200})
        }

        labels = {
            'code' : 'Code',
            'description' : 'Description',
            'status' : 'Status',
            'treatment' : 'Treatment'
        }


def diagnosis_list(request, template_name='diagnoses/diagnosis_list.html'):
    diagnosis = Diagnosis.objects.all()
    data = {}
    data['object_list'] = diagnosis
    return render(request, template_name, data)


def diagnosis_view(request, pk, template_name='diagnoses/diagnosis_detail.html'):
    diagnosis = get_object_or_404(Diagnosis, pk=pk)
    return render(request, template_name, {'object': diagnosis})


# todo delete
def diagnosis_create(request, template_name='diagnoses/diagnosis_form.html'):
    form = DiagnosisForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('diagnosis_list')
    return render(request, template_name, {'form': form})


def diagnosis_create_for_appointment(request, appointmentpk, template_name='diagnoses/diagnosis_form.html'):

    form = DiagnosisForm(request.POST or None)
    appointment = get_object_or_404(Appointment, pk=appointmentpk)
    form.instance.appointment = appointment
    if form.is_valid():
        form.save()
        return  redirect('animal_view', appointment.animal.pk)
    return render(request, template_name, {'form':form})


def diagnosis_update(request, pk, template_name='diagnoses/diagnosis_form.html'):
    diagnosis = get_object_or_404(Diagnosis, pk=pk)
    animal = get_object_or_404(Animal, pk= diagnosis.appointment.animal.pk)
    form = DiagnosisForm(request.POST or None, instance=diagnosis)
    if form.is_valid():
        form.save()
        return redirect('animal_view', animal.pk)
    return render(request, template_name, {'form': form})


def diagnosis_delete(request, pk, template_name='diagnoses/diagnosis_confirm_delete.html'):
    diagnosis = get_object_or_404(Diagnosis, pk=pk)
    animal = get_object_or_404(Animal, pk= diagnosis.appointment.animal.pk)
    if request.method == 'POST':
        diagnosis.delete()
        return redirect('animal_view', animal.pk)
    return render(request, template_name, {'object': diagnosis})


def diagnosis_search(request, template_name='diagnoses/diagnosis_search.html'):
    query = request.GET.get('q')
    results = Diagnosis.objects.filter(Q(code__icontains=query) | Q(description__icontains=query) | Q(status__icontains=query) |
                                    Q(treatment__icontains=query))
    data={}
    data['object_list'] = results
    return render(request, template_name, data)


def diagnosis_sort(request, template_name='diagnoses/diagnosis_sort.html'):
    results = Diagnosis.objects.all()
    data = {}
    if 'dropdown' in request.GET:
        answer = request.GET['dropdown']
        data['object_list'] = sorted(results, key=attrgetter(answer))
    else:
        data['object_list'] = results
    return render(request, template_name, data)

db_assignment/diagnoses/templates/diagnoses/diagnosis_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Diagnoses Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

{% endblock %}

db_assignment/diagnoses/templates/diagnoses/diagnosis_detail.html
{% extends "base.html" %}
{% block content %}

<h1>Diagnosis Details</h1>
    <table class="pure-table" ><tbody>
        <tr>
            <td>Description: </td>
            <td>{{ object.description }}</td>
        </tr>
        <tr>
            <td>Code: </td>
            <td>{{object.code}}</td>
        </tr>
        <tr>
            <td>Status: </td>
            <td>{{ object.status }}</td>
        </tr>
        <tr>
            <td>Treatment: </td>
            <td>{{ object.treatment }}</td>
        </tr>
        </tbody>
    </table>

    <button class="pure-button" onclick="location.href='{% url "appointment_view" object.appointment.pk %}'" type="button">back to appointment</button>
    <button class="pure-button" onclick="location.href='{% url "animal_view" object.appointment.animal.pk %}'" type="button">back to animal</button>


    <h3>Medications</h3>

<table class="pure-table"><thead>
<tr>
    <th>Name</th>
    <th>Cost</th>
    <th>Other Details</th>
    <th>Edit</th>
    <th>Delete</th>
</tr>
</thead><tbody>
{% for diagnosismedication in object.diagnosismedication_set.all %}
<tr>
    <td> {{ diagnosismedication.medication.name }}</td>
    <td> {{ diagnosismedication.medication.cost }}</td>
    <td> {{ diagnosismedication.medication.otherdetails }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosismedication_edit" diagnosismedication.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosismedication_delete" diagnosismedication.pk %}'" type="button">delete</button></td>
</tr>
{% endfor %}
</tbody></table>
<td>
<button class="pure-button" onclick="location.href='{% url "diagnosismedication_new" object.pk %}'" type="button">add a medication</button>
</td>

<h3>Procedures</h3>
<table class="pure-table"><thead>
<tr>
    <th>Name</th>
    <th>Cost</th>
    <th>Other Details</th>
    <th>Edit</th>
    <th>Delete</th>
</tr>
</thead><tbody>
{% for diagnosismedicalprocedure in object.diagnosismedicalprocedure_set.all %}
<tr>
    <td> {{ diagnosismedicalprocedure.medicalprocedure.name }}</td>
    <td> {{ diagnosismedicalprocedure.medicalprocedure.cost }}</td>
    <td> {{ diagnosismedicalprocedure.medicalprocedure.otherdetails }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosisprocedure_edit" diagnosismedicalprocedure.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosisprocedure_delete" diagnosismedicalprocedure.pk %}'" type="button">delete</button></td>
</tr>
{% endfor %}
</tbody></table>
<td>
<button class="pure-button" onclick="location.href='{% url "diagnosisprocedure_new" object.pk %}'" type="button">Add a procedure</button>
</td>

{% endblock %}

db_assignment/diagnoses/templates/diagnoses/diagnosis_form.html
{% extends "base.html" %}

{% block content %}

<h1>Diagnoses Edit</h1>
<form class="pure-form" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

db_assignment/diagnoses/templates/diagnoses/diagnosis_list.html
{% extends "base.html" %}
{% block content %}

<h1>Diagnoses</h1>

<form method="GET" action="{% url 'diagnosis_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<form method="GET" action="{% url 'diagnosis_sort' %}">
    <select name="dropdown">
        <option selected="selected" disabled>Sort by:</option>
        <option value="code">code</option>
        <option value="description">description</option>
        <option value="status">status</option>
        <option value="treatment">treatment</option>
    </select>
    <input type="submit" value="Ok">
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Code</th>
    <th>Description</th>
    <th>Status</th>
    <th>Treatment</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for diagnosis in object_list %}
    <tr>
    <td>{{ diagnosis.code }}</td>
    <td>{{ diagnosis.description }}</td>
    <td>{{ diagnosis.status }}</td>
    <td>{{ diagnosis.treatment }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_view" diagnosis.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_edit" diagnosis.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_delete" diagnosis.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

    <button class="pure-button" onclick="location.href='{% url "diagnosis_new" %}'" type="button">New Diagnosis</button>
{% endblock %}

db_assignment/diagnoses/templates/diagnoses/diagnosis_search.html
{% extends "base.html" %}
{% block content %}

<h1>Results</h1>

<form method="GET" action="{% url 'diagnosis_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Code</th>
    <th>Description</th>
    <th>Status</th>
    <th>Treatment</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for results in object_list %}
    <tr>
    <td>{{ results.code }}</td>
    <td>{{ results.description }}</td>
    <td>{{ results.status }}</td>
    <td>{{ results.treatment }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_view" results.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_edit" results.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_delete" results.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

db_assignment/diagnoses/templates/diagnoses/diagnosis_sort.html
{% extends "base.html" %}
{% block content %}

<h1>Diagnosis</h1>

<form method="GET" action="{% url 'diagnosis_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<form method="GET" action="{% url 'diagnosis_sort' %}">
    <select name="dropdown">
        <option selected="selected" disabled>Sort by:</option>
        <option value="code">code</option>
        <option value="description">description</option>
        <option value="status">status</option>
        <option value="treatment">treatment</option>
    </select>
    <input type="submit" value="Ok">
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Code</th>
    <th>Description</th>
    <th>Status</th>
    <th>Treatment</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for results in object_list %}
    <tr>
    <td>{{ results.code }}</td>
    <td>{{ results.description }}</td>
    <td>{{ results.status }}</td>
    <td>{{ results.treatment }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_view" results.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_edit" results.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "diagnosis_delete" results.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}