db_assignment/animals/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.animal_list, name='animal_list'),
    path('view/<int:pk>', views.animal_view, name='animal_view'),
    path('new', views.animal_create, name='animal_new'),
    path('new/<int:clientpk>', views.animal_create_for_client, name='animal_new_for_client'),
    path('edit/<int:pk>', views.animal_update, name='animal_edit'),
    path('delete/<int:pk>', views.animal_delete, name='animal_delete'),
    path('search/', views.animal_search, name='animal_search'),
    path('sort/', views.animal_sort, name='animal_sort'),
    path('new_appointment/<int:pk>', views.animal_new_appointment, name='animal_new_appointment')
]

db_assignment/db_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

admin.autodiscover()

urlpatterns = [

    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls')),
    path('animals/', include('animals.urls')),
    path('species/', include('species.urls')),
    path('vets/', include('vets.urls')),
    path('diagnoses/', include('diagnoses.urls')),
    path('appointments/', include('appointments.urls')),
    path('medicalprocedures/', include('medicalprocedures.urls')),
    path('medications/', include('medications.urls')),
    path('notes/', include('notes.urls')),
    path('diagnosesmedications/', include('diagnosesmedications.urls')),
    path('dignosesprocedures/', include('diagnosesprocedures.urls')),
    path('', include('clients.urls'))
    
]

db_assignment/vets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.vet_list, name='vet_list'),
    path('view/<int:pk>', views.vet_view, name='vet_view'),
    path('new', views.vet_create, name='vet_new'),
    path('edit/<int:pk>', views.vet_update, name='vet_edit'),
    path('delete/<int:pk>', views.vet_delete, name='vet_delete'),
    path('search', views.vet_search, name='vet_search'),
    path('sort/', views.vet_sort, name='vet_sort')
]

db_assignment/models/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.urls import reverse
from django.db import connection

from models.validators import validate_positive


class Client(models.Model):
    clientid = models.AutoField(db_column='ClientID', primary_key=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20)  # Field name made lowercase.
    registrationdate = models.DateField(db_column='RegistrationDate')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Clients'

    def __str__(self):
        return self.firstname + " " + self.lastname

    def get_absolute_url(self):
        return reverse('client_edit', kwargs={'pk': self.pk})




class Animal(models.Model):
    animalid = models.AutoField(db_column='AnimalID', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=20)  # Field name made lowercase.
    registrationdate = models.DateField(db_column='RegistrationDate')  # Field name made lowercase.
    birth = models.DateField(db_column='Birth')  # Field name made lowercase.
    gender = models.CharField(db_column='Gender', max_length=6)  # Field name made lowercase.
    height = models.FloatField(db_column='Height', validators=[validate_positive])  # Field name made lowercase.
    weight = models.FloatField(db_column='Weight', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.
    client = models.ForeignKey('Client', models.CASCADE, db_column='Clients_ClientID')  # Field name made lowercase.
    species = models.ForeignKey('Species', models.CASCADE, db_column='Species_Name')  # Field name made lowercase.
    vet = models.ForeignKey('Vet', models.SET_NULL, db_column='Vets_VetID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Animals'

    def __str__(self):
        return self.name

    def _get_last_visit(self):
        with connection.cursor() as cursor:
            cursor.execute("select last_visit(%s)", [self.pk])
            row = cursor.fetchone()
        if row == (None,):
            return "Never"

        return row[0]

    last_visit = property(_get_last_visit)



class Appointment(models.Model):
    appointmentid = models.AutoField(db_column='AppointmentID', primary_key=True)  # Field name made lowercase.
    date = models.DateField(db_column='Date')  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    details = models.CharField(db_column='Details', max_length=20)  # Field name made lowercase.
    vet = models.ForeignKey('Vet', models.CASCADE, db_column='Vets_VetID')  # Field name made lowercase.
    animal = models.ForeignKey(Animal, models.CASCADE, db_column='Animals_AnimalID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Appointments'

    def __str__(self):
        return str(self.date) + " " + str(self.vet) + " " + str(self.animal)

    def custom_save(self):
        with connection.cursor() as cursor:
            cursor.callproc('new_visit', [self.date, self.status, self.details, self.vet.pk, self.animal.pk])
            row = cursor.fetchone()
        return row



class Diagnosis(models.Model):
    diagnosisid = models.AutoField(db_column='DiagnosisID', primary_key=True)  # Field name made lowercase.
    code = models.CharField(db_column='Code', max_length=20)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200)  # Field name made lowercase.
    status = models.CharField(db_column='Status', max_length=20)  # Field name made lowercase.
    treatment = models.CharField(db_column='Treatment', max_length=200)  # Field name made lowercase.
    appointment = models.ForeignKey(Appointment, models.CASCADE, db_column='Appointments_AppointmentID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Diagnoses'

    def __str__(self):
        return "diagnosis " + str(self.pk) + self.description

class MedicalProcedure(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'MedicalProcedures'

    def __str__(self):
        return self.name + " " + str(self.cost)


class Medication(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    cost = models.FloatField(db_column='Cost', validators=[validate_positive])  # Field name made lowercase.
    otherdetails = models.CharField(db_column='OtherDetails', max_length=200, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Medications'

    def __str__(self):
        return self.name + " " + str(self.cost)

class DiagnosisMedicalProcedure(models.Model):
    diagnosis_medicalprocedureid = models.AutoField(db_column='Diagnoses_MedicalProceduresID', primary_key=True)  # Field name made lowercase.
    diagnosis = models.ForeignKey(Diagnosis, models.CASCADE, db_column='Diagnoses_DiagnosisID')  # Field name made lowercase.
    medicalprocedure = models.ForeignKey('MedicalProcedure', models.CASCADE, db_column='MedicalProcedures_Name')

    class Meta:
        managed = False
        db_table = 'Diagnoses_MedicalProcedures'

    def __str__(self):
        return  self.medicalprocedure.name + " " + str(self.medicalprocedure.cost)


class DiagnosisMedication(models.Model):
    diagnosis_medicationid = models.AutoField(db_column='Diagnoses_MedicationsID', primary_key=True)  # Field name made lowercase.
    medication = models.ForeignKey('Medication', models.CASCADE, db_column='Medications_Name')  # Field name made lowercase.
    diagnosis = models.ForeignKey(Diagnosis, models.CASCADE, db_column='Diagnoses_DiagnosisID')

    class Meta:
        managed = False
        db_table = 'Diagnoses_Medications'

    def __str__(self):
        return  self.medication.name + " " + str(self.medication.cost)


class Note(models.Model):
    noteid = models.AutoField(db_column='NoteID', primary_key=True)  # Field name made lowercase.
    date = models.DateField(db_column='NoteDate')  # Field name made lowercase.
    content = models.CharField(db_column='Content', max_length=200)  # Field name made lowercase.
    animal = models.ForeignKey(Animal, models.CASCADE, db_column='Animals_AnimalID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Notes'

    def get_absolute_url(self):
        return reverse('note_edit', kwargs={'pk': self.pk})

    def __str__(self):
        return "note " + self.pk + str(self.date)


class Species(models.Model):
    name = models.CharField(db_column='Name', primary_key=True, max_length=20)  # Field name made lowercase.
    obligatoryprocedures = models.CharField(db_column='ObligatoryProcedures', max_length=20)  # Field name made lowercase.
    description = models.CharField(db_column='Description', max_length=200)  # Field name made lowercase.
    legalissues = models.CharField(db_column='LegalIssues', max_length=200)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Species'

    def __str__(self):
        return  self.name

    def get_absolute_url(self):
        return reverse('species_edit', kwargs={'pk': self.pk})


class Vet(models.Model):
    vetid = models.AutoField(db_column='VetID', primary_key=True)  # Field name made lowercase.
    firstname = models.CharField(db_column='FirstName', max_length=20)  # Field name made lowercase.
    lastname = models.CharField(db_column='LastName', max_length=20)  # Field name made lowercase.
    qualifications = models.CharField(db_column='Qualifications', max_length=20)  # Field name made lowercase.
    birth = models.DateField(db_column='Birth')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Vets'

    def __eq__(self, other):
        return str(self) == str(other)

    def __lt__(self, other):
        return str(self) < str(other)


    def __gt__(self, other):
        return str(self) > str(other)


    def __str__(self):
        return self.firstname + " " + self.lastname

    def get_absolute_url(self):
        return reverse('vet_edit', kwargs={'pk': self.pk})

db_assignment/animals/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import ModelForm
from django import forms

from django.db.models import Q
from models.models import Animal, Client, Vet, Appointment
from appointments.views import AppointmentForm
from operator import attrgetter


class AnimalForm(ModelForm):
    class Meta:
        model = Animal
        fields = ['name', 'registrationdate', 'birth', 'gender',
                  'height', 'weight', 'otherdetails', 'species', 'vet']
        widgets = {'otherdetails': forms.Textarea(attrs={'class': 'text-input', 'size': 200})}
        labels = {
            'name' : 'Name',
            'registrationdate' :  'Registration Date (YYYY-MM-DD)',
            'birth' : 'Birth (YYYY-MM-DD)',
            'gender' : 'Gender',
            'height' : 'Height',
            'weight' :  'Weight',
            'otherdetails' : 'Other Details',
            'species' : 'Species',
            'vet' : 'Vet'
        }


# show all animals
def animal_list(request, template_name='animals/animal_list.html'):
    animal = Animal.objects.all()

    data = {}
    data['object_list'] = animal
    return render(request, template_name, data)


# show animal's details
def animal_view(request, pk, template_name='animals/animal_detail.html'):
    animal = get_object_or_404(Animal, pk=pk)
    return render(request, template_name, {'object': animal, 'last_visit': animal.last_visit})


def animal_create(request, template_name='animals/animal_form.html'):
    form = AnimalForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('animal_list')
    return render(request, template_name, {'form': form})


# add an animal and go back to client
def animal_create_for_client(request, clientpk, template_name='animals/animal_form.html'):
    form = AnimalForm(request.POST or None)
    form.instance.client = get_object_or_404(Client,pk=clientpk)
    if form.is_valid():
        form.save()
        return redirect('animal_view', form.instance.pk)
    return render(request, template_name, {'form': form})


def animal_new_appointment(request, pk, template_name='animals/animal_form.html'):
    form = AnimalForm(request.POST or None)
    animal = get_object_or_404(Animal, pk=pk)
    form.instance.animal = animal
    if form.is_valid():
        appointment = form.instance
        appointment.custom_save()
        appointment.new_visit
        return redirect('animal_list', appointment.vet.pk)
    return render(request, template_name, {'form': form})


# edit an animal and go back to the client
def animal_update(request, pk, template_name='animals/animal_form.html'):
    animal = get_object_or_404(Animal, pk=pk)
    form = AnimalForm(request.POST or None, instance=animal)
    if form.is_valid():
        form.save()
        return redirect('animal_view', animal.pk)
    return render(request, template_name, {'form': form})


# delete an animal and go back to the client
def animal_delete(request, pk, template_name='animals/animal_confirm_delete.html'):
    animal = get_object_or_404(Animal, pk=pk)
    client = animal.client
    if request.method == 'POST':
        animal.delete()
        return redirect('client_view', client.pk)
    return render(request, template_name, {'object': animal})


def animal_search(request, template_name='animals/animal_search.html'):
    query = request.GET.get('q')
    results = Animal.objects.filter(Q(name__icontains=query) | Q(registrationdate__icontains=query) | Q(birth__icontains=query) |
                                    Q(gender__icontains=query) | Q(height__icontains=query) | Q(weight__icontains=query) |
                                    Q(otherdetails__icontains=query) |Q(vet__firstname__icontains=query) | Q(vet__lastname__icontains=query) |
                                    Q(species__name__icontains=query))
    data={}
    data['object_list'] = results
    return render(request, template_name, data)


def animal_sort(request, template_name='animals/animal_sort.html'):
    results = Animal.objects.all()
    data = {}
    if 'dropdown' in request.GET:
        answer = request.GET['dropdown']
        data['object_list'] = sorted(results, key=attrgetter(answer))
    else:
        data['object_list'] = results
    return render(request, template_name, data)

db_assignment/animals/templates/animals/animal_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Animal Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

db_assignment/animals/templates/animals/animal_detail.html
{% extends "base.html" %}
{% block content %}

<h1>Animal Details</h1>
    <button class="pure-button" onclick="location.href='{% url "client_view"  object.client.pk%}'" type="button">Back to Client</button>

<table class="pure-table">
<tbody>
    <tr>
        <td>Name: </td>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <td>Birth: </td>
        <td>{{ object.birth }}</td>
    </tr>
    <tr>
        <td>Gender:</td>
        <td>{{ object.gender }}</td>
    </tr>
    <tr>
        <td>Species:</td>
        <td>{{ object.species }}</td>
    </tr>
    <tr>
        <td>Height:</td>
        <td>{{ object.height }}</td>
    </tr>
    <tr>
        <td>Weight:</td>
        <td>{{ object.weight }}</td>
    </tr>
    <tr>
        <td>Registration Date:</td>
        <td>{{ object.registrationdate }}</td>
    </tr>
    <tr>
        <td>Vet:</td>
        <td>{{ object.vet }}</td>
    </tr>
    <tr>
        <td>Other details:</td>
        <td>{{ object.otherdetails }}</td>
    </tr>
    <tr>
        <td>Last Visit:</td>
        <td>{{ last_visit }}</td>
    </tr>
</tbody>
</table>
<table><tbody>
    <tr>
        <td><button class="pure-button" onclick="location.href='{% url "animal_edit" object.pk %}'" type="button">Edit Animal</button></td>
    </tr>

</tbody></table>

<h3>Appointments
    <button class="pure-button" onclick="location.href='{% url "appointment_new_for_animal" object.pk %}'" type="button">Create New</button>
</h3>

<table class="pure-table"><thead>
    <tr>
        <th>Date</th>
        <th>Vet</th>
        <th>Details</th>
        <th>Status</th>
        <th>Edit</th>
        <th>View</th>
        <th>Delete</th>
        <th>Add a diagnosis</th>
    </tr>
</thead>
    {% for appointment in object.appointment_set.all %}
    <tr>
        <td>{{ appointment.date }}</td>
        <td>{{ appointment.vet }}</td>
        <td>{{ appointment.details }}</td>
        <td>{{ appointment.status }}</td>
        <td><button class="pure-button" onclick="location.href='{% url "appointment_view" appointment.pk %}'" type="button">view</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "appointment_edit" appointment.pk %}'" type="button">edit</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "appointment_delete" appointment.pk %}'" type="button">delete</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "diagnosis_new_for_appointment" appointment.pk %}'" type="button">add a diagnosis</button></td>
    </tr>
    {% endfor %}
<tbody>
</tbody></table>

<h3>Notes
<button class="pure-button" onclick="location.href='{% url "note_new_for_animal" object.pk %}'" type="button">Create New</button>
</h3>
<table class="pure-table"><thead>
    <tr>
        <th>Date</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for note in object.note_set.all %}
    <tr>
        <td>{{ note.date }}</td>
        <td><button class="pure-button" onclick="location.href='{% url "note_view" note.pk %}'" type="button">view</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "note_edit" note.pk %}'" type="button">edit</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "note_delete" note.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

<h3>Diagnoses
</h3>


<table class="pure-table"><thead>
    <tr>
        <th>Date</th>
        <th>Status</th>
        <th>Description</th>
        <th>Treatment</th>
        <th>Code</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for appointment in object.appointment_set.all %}
    {% for diagnosis in appointment.diagnosis_set.all %}
    <tr>
        <td>{{ diagnosis.appointment.date }}</td>
        <td>{{ diagnosis.status }}</td>
        <td>{{ diagnosis.description }}</td>
        <td>{{ diagnosis.treatment }}</td>
        <td>{{ diagnosis.code }}</td>
        <td><button class="pure-button" onclick="location.href='{% url "diagnosis_view" diagnosis.pk %}'" type="button">view</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "diagnosis_edit" diagnosis.pk %}'" type="button">edit</button></td>
        <td><button class="pure-button" onclick="location.href='{% url "diagnosis_delete" diagnosis.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
    {% endfor %}
</tbody>
</table>
{% endblock %}

db_assignment/animals/templates/animals/animal_form.html
{% extends "base.html" %}
{% block content %}
<h1>Animal Edit</h1>
<form class="pure-form" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

db_assignment/animals/templates/animals/animal_list.html
{% extends "base.html" %}
{% block content %}
<h1>Animals</h1>

<form method="GET" action="{% url 'animal_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<form method="GET" action="{% url 'animal_sort' %}">
    <select name="dropdown">
        <option selected="selected" disabled>Sort by:</option>
        <option value="name">name</option>
        <option value="registrationdate">registration date</option>
        <option value="birth">birth</option>
        <option value="gender">gender</option>
        <option value="height">height</option>
        <option value="weight">weight</option>
        <option value="species.name">species</option>
    </select>
    <input type="submit" value="Ok">
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Name</th>
    <th>Registration date</th>
    <th>Birth</th>
    <th>Gender</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Species name</th>
    <th>Other details</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for animal in object_list %}
    <tr>
    <td>{{ animal.name }}</td>
    <td>{{ animal.registrationdate }}</td>
    <td>{{ animal.birth }}</td>
    <td>{{ animal.gender }}</td>
    <td>{{ animal.height }}</td>
    <td>{{ animal.weight }}</td>
    <td>{{ animal.species }}</td>
    <td>{{ animal.otherdetails }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_view" animal.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_edit" animal.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_delete" animal.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

db_assignment/animals/templates/animals/animal_search.html
{% extends "base.html" %}
{% block content %}
<h1>Results</h1>

<form method="GET" action="{% url 'animal_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<table class="pure-table">
<thead>
    <tr>
    <th>Name</th>
    <th>Registration date</th>
    <th>Birth</th>
    <th>Gender</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Species name</th>
    <th>Other details</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for results in object_list %}
    <tr>
    <td>{{ results.name }}</td>
    <td>{{ results.registrationdate }}</td>
    <td>{{ results.birth }}</td>
    <td>{{ results.gender }}</td>
    <td>{{ results.height }}</td>
    <td>{{ results.weight }}</td>
    <td>{{ results.species }}</td>
    <td>{{ results.otherdetails }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_view" results.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_edit" results.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_delete" results.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}

db_assignment/animals/templates/animals/animal_sort.html
{% extends "base.html" %}
{% block content %}
<h1>Animals</h1>

<form method="GET" action="{% url 'animal_search' %}">
<input name="q" value="{{ request.GET.q }}" placeholder="search">
<button class="btn btn-success" type="submit">
    Search
</button>
</form>

<form method="GET" action="{% url 'animal_sort' %}">
    <select name="dropdown">
        <option selected="selected" disabled>Sort by:</option>
        <option value="name">name</option>
        <option value="registrationdate">registration date</option>
        <option value="birth">birth</option>
        <option value="gender">gender</option>
        <option value="height">height</option>
        <option value="weight">weight</option>
        <option value="species.name">species</option>
    </select>
    <input type="submit" value="Ok">
</form>


<table class="pure-table">
<thead>
    <tr>
    <th>Name</th>
    <th>Registration date</th>
    <th>Birth</th>
    <th>Gender</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Species name</th>
    <th>Other details</th>
    <th>View</th>
    <th>Edit</th>
    <th>Delete</th>
    </tr>
</thead>
<tbody>
    {% for results in object_list %}
    <tr>
    <td>{{ results.name }}</td>
    <td>{{ results.registrationdate }}</td>
    <td>{{ results.birth }}</td>
    <td>{{ results.gender }}</td>
    <td>{{ results.height }}</td>
    <td>{{ results.weight }}</td>
    <td>{{ results.species }}</td>
    <td>{{ results.otherdetails }}</td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_view" results.pk %}'" type="button">view</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_edit" results.pk %}'" type="button">edit</button></td>
    <td><button class="pure-button" onclick="location.href='{% url "animal_delete" results.pk %}'" type="button">delete</button></td>
    </tr>
    {% endfor %}
</tbody>
</table>

{% endblock %}